const dummyData = {
  categories: [
    { name: "Hambúrgueres", description: "Hambúrgueres suculentos na grelha" },
    { name: "Pizzas", description: "Pizzas assadas no forno com muito queijo" },
    { name: "Burritos", description: "Delícias mexicanas enroladas" },
    { name: "Sanduíches", description: "Sanduíches recheados e empilhados" },
    { name: "Wraps", description: "Wraps enrolados cheios de sabor" },
    { name: "Bowls", description: "Bowls equilibrados de arroz e proteína" },
  ],

  customizations: [
    // Adicionais
    { name: "Queijo Extra", price: 25, type: "topping" },
    { name: "Jalapeños", price: 20, type: "topping" },
    { name: "Cebola", price: 10, type: "topping" },
    { name: "Azeitonas", price: 15, type: "topping" },
    { name: "Cogumelos", price: 18, type: "topping" },
    { name: "Tomates", price: 10, type: "topping" },
    { name: "Bacon", price: 30, type: "topping" },
    { name: "Abacate", price: 35, type: "topping" },

    // Acompanhamentos
    { name: "Coca-Cola", price: 30, type: "side" },
    { name: "Batata Frita", price: 35, type: "side" },
    { name: "Pão de Alho", price: 40, type: "side" },
    { name: "Nuggets de Frango", price: 50, type: "side" },
    { name: "Chá Gelado", price: 28, type: "side" },
    { name: "Salada", price: 33, type: "side" },
    { name: "Batata Rústica", price: 38, type: "side" },
    { name: "Palito de Mussarela", price: 45, type: "side" },
    { name: "Milho Verde", price: 25, type: "side" },
    { name: "Bolo de Chocolate Quente", price: 42, type: "side" },
  ],

  menu: [
    {
      name: "Cheeseburger Clássico",
      description: "Carne bovina, queijo, alface, tomate",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/044/844/600/large_2x/homemade-fresh-tasty-burger-with-meat-and-cheese-classic-cheese-burger-and-vegetable-ai-generated-free-png.png",
      price: 25.99,
      rating: 4.5,
      calories: 550,
      protein: 25,
      category_name: "Hambúrgueres",
      customizations: ["Queijo Extra", "Coca-Cola", "Batata Frita", "Cebola", "Bacon"],
    },
    {
      name: "Pizza de Pepperoni",
      description: "Recheada com queijo e fatias de pepperoni",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/023/742/417/large_2x/pepperoni-pizza-isolated-illustration-ai-generative-free-png.png",
      price: 30.99,
      rating: 4.7,
      calories: 700,
      protein: 30,
      category_name: "Pizzas",
      customizations: [
        "Queijo Extra",
        "Jalapeños",
        "Pão de Alho",
        "Coca-Cola",
        "Azeitonas",
      ],
    },
    {
      name: "Burrito de Feijão",
      description: "Recheado com feijão, arroz e salsa",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/055/133/581/large_2x/deliciously-grilled-burritos-filled-with-beans-corn-and-fresh-vegetables-served-with-lime-wedge-and-cilantro-isolated-on-transparent-background-free-png.png",
      price: 20.99,
      rating: 4.2,
      calories: 480,
      protein: 18,
      category_name: "Burritos",
      customizations: ["Jalapeños", "Chá Gelado", "Batata Frita", "Salada"],
    },
    {
      name: "Hambúrguer BBQ com Bacon",
      description: "Molho BBQ defumado, bacon crocante, cheddar",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/060/236/245/large_2x/a-large-hamburger-with-cheese-onions-and-lettuce-free-png.png",
      price: 27.5,
      rating: 4.8,
      calories: 650,
      protein: 29,
      category_name: "Hambúrgueres",
      customizations: ["Cebola", "Batata Frita", "Coca-Cola", "Bacon", "Abacate"],
    },
    {
      name: "Wrap Caesar de Frango",
      description: "Frango grelhado, alface, molho Caesar",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/048/930/603/large_2x/caesar-wrap-grilled-chicken-isolated-on-transparent-background-free-png.png",
      price: 21.5,
      rating: 4.4,
      calories: 490,
      protein: 28,
      category_name: "Wraps",
      customizations: ["Queijo Extra", "Coca-Cola", "Batata Rústica", "Tomates"],
    },
    {
      name: "Sanduíche de Legumes Grelhados",
      description: "Legumes assados, pesto, queijo",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/047/832/012/large_2x/grilled-sesame-seed-bread-veggie-sandwich-with-tomato-and-onion-free-png.png",
      price: 19.99,
      rating: 4.1,
      calories: 420,
      protein: 19,
      category_name: "Sanduíches",
      customizations: ["Cogumelos", "Azeitonas", "Palito de Mussarela", "Chá Gelado"],
    },
    {
      name: "Hambúrguer Duplo",
      description: "Dois hambúrgueres suculentos e queijo",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/060/359/627/large_2x/double-cheeseburger-with-lettuce-tomatoes-cheese-and-sesame-bun-free-png.png",
      price: 32.99,
      rating: 4.9,
      calories: 720,
      protein: 35,
      category_name: "Hambúrgueres",
      customizations: [
        "Queijo Extra",
        "Cebola",
        "Batata Frita",
        "Coca-Cola",
        "Nuggets de Frango",
      ],
    },
    {
      name: "Wrap Paneer Tikka",
      description: "Paneer apimentado, chutney de hortelã, legumes",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/057/913/530/large_2x/delicious-wraps-a-tantalizing-array-of-wraps-filled-with-vibrant-vegetables-succulent-fillings-and-fresh-ingredients-artfully-arranged-for-a-mouthwatering-culinary-experience-free-png.png",
      price: 23.99,
      rating: 4.6,
      calories: 470,
      protein: 20,
      category_name: "Wraps",
      customizations: ["Jalapeños", "Tomates", "Salada", "Batata Frita", "Chá Gelado"],
    },
    {
      name: "Bowl Burrito Mexicano",
      description: "Arroz, feijão, milho, guacamole, salsa",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/057/466/374/large_2x/healthy-quinoa-bowl-with-avocado-tomato-and-black-beans-ingredients-free-png.png",
      price: 26.49,
      rating: 4.7,
      calories: 610,
      protein: 24,
      category_name: "Bowls",
      customizations: ["Abacate", "Milho Verde", "Salada", "Chá Gelado"],
    },
    {
      name: "Sanduíche de Frango Apimentado",
      description: "Frango crocante, molho apimentado, picles",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/051/814/008/large_2x/a-grilled-chicken-sandwich-with-lettuce-and-tomatoes-free-png.png",
      price: 24.99,
      rating: 4.3,
      calories: 540,
      protein: 26,
      category_name: "Sanduíches",
      customizations: [
        "Jalapeños",
        "Cebola",
        "Batata Frita",
        "Coca-Cola",
        "Bolo de Chocolate Quente",
      ],
    },
    {
      name: "Pizza Margherita Clássica",
      description: "Tomate, mussarela, manjericão fresco",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/058/700/845/large_2x/free-isolated-on-transparent-background-delicious-pizza-topped-with-fresh-tomatoes-basil-and-melted-cheese-perfect-for-food-free-png.png",
      price: 26.99,
      rating: 4.1,
      calories: 590,
      protein: 21,
      category_name: "Pizzas",
      customizations: ["Queijo Extra", "Azeitonas", "Coca-Cola", "Pão de Alho"],
    },
    {
      name: "Bowl de Proteína",
      description: "Frango grelhado, quinoa, legumes",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/056/106/379/large_2x/top-view-salad-with-chicken-avocado-tomatoes-and-lettuce-free-png.png",
      price: 29.99,
      rating: 4.8,
      calories: 580,
      protein: 38,
      category_name: "Bowls",
      customizations: ["Abacate", "Salada", "Milho Verde", "Chá Gelado"],
    },
    {
      name: "Burrito de Paneer",
      description: "Cubos de paneer, masala apimentado, arroz, feijão",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/056/565/254/large_2x/burrito-with-cauliflower-and-vegetables-free-png.png",
      price: 24.99,
      rating: 4.2,
      calories: 510,
      protein: 22,
      category_name: "Burritos",
      customizations: ["Jalapeños", "Batata Frita", "Pão de Alho", "Coca-Cola"],
    },
    {
      name: "Sanduíche Club de Frango",
      description: "Frango grelhado, alface, queijo, tomate",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/060/364/135/large_2x/a-flavorful-club-sandwich-with-turkey-bacon-and-fresh-vegetables-sliced-and-isolated-on-a-transparent-background-free-png.png",
      price: 27.49,
      rating: 4.5,
      calories: 610,
      protein: 31,
      category_name: "Sanduíches",
      customizations: ["Bacon", "Tomates", "Palito de Mussarela", "Chá Gelado"],
    },
  ],
};

export default dummyData;
